spring.application.name=Yoestudio

# NEON 
spring.datasource.url= jdbc:postgresql://neondb_owner:npg_n5CFb8WQILkq@ep-gentle-mouse-amcubxzv-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${BD_PASS:npg_n5CFb8WQILkq}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP (optimizado)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.leak-detection-threshold=60000

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Permitir que los campos de texto sean grandes para Gemini
spring.jpa.properties.hibernate.type.preferred_duration_jdbc_type=VARCHAR

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

#Geminis 
spring.ai.google.ai.api-key=${SPRING_AI_GOOGLE_AI_API_KEY}
# Opcional: También puedes definir el modelo globalmente aquí
spring.ai.google.ai.chat.options.model=gemini-3-flash
