spring.application.name=Yoestudio
server.address=0.0.0.0
server.port=3000

spring.data.mongodb.uri=${MONGO_URI}

spring.ai.google.ai.api-key=${SPRING_AI_GOOGLE_AI_API_KEY}
spring.ai.google.ai.chat.options.model=gemini-2.5-flash
gemini.model.name=gemini-2.5-flash

spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=neondb_owner
spring.datasource.password=npg_n5CFb8WQILkq
spring.datasource.driver-class-name=org.postgresql.Driver

app.output.dir=./output

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.jpa.hibernate.ddl-auto=update
